In [1]:
s = 'a\nb\tc'

In [2]:
print(s)

a
b	c


In [12]:
len(s) ## each charactr is adds to the length. \n is one character. \b is another character.

5

In [4]:
a = 'b  c'

In [5]:
len(a)

4

In [6]:
print(a)

b  c


In [10]:
b = """
aaaaaa
bbb'bbbbbb""bbbbb'bbbb
ccccccccc
"""

In [11]:
b

'\naaaaaa\nbbb\'bbbbbb""bbbbb\'bbbb\nccccccccc\n'

In [23]:
c = """
a'b
"""

In [24]:
print(c)


a'b



In [18]:
len(c)

4

In [32]:
L = [1,2,3,4,5,6]

In [33]:
L.pop(-2)

5

In [34]:
L


[1, 2, 3, 4, 6]

In [42]:
 M = [[1,2,3],[4,5,6],[6,10,12]]

In [45]:
col2 = [x[1] for x in M if x[1] % 2 ==0]

In [46]:
col2

[2, 10]

In [49]:
diag = [M[i][i] for i in range(3)]

In [50]:
diag

[1, 5, 12]

In [52]:
type(range(4))

range

In [53]:
list(range(4))

[0, 1, 2, 3]

In [54]:
range(4)

range(0, 4)

In [57]:
set(range(4))

{0, 1, 2, 3}

In [61]:
G = (sum(x) for x in M)

In [64]:
next(G)

28

In [65]:
M

[[1, 2, 3], [4, 5, 6], [6, 10, 12]]

In [66]:
[sum(x) for x in M]

[6, 15, 28]

In [67]:
list(map(sum, M))

[6, 15, 28]

In [68]:
{sum(x) for x in M}

{6, 15, 28}

In [69]:
(sum(x) for x in M)

<generator object <genexpr> at 0x0000017FD8644048>

In [72]:
{x : sum(M[x]) for x in range(3)}

{0: 6, 1: 15, 2: 28}

In [74]:
M[0]

[1, 2, 3]

In [76]:
import numpy as np

In [77]:
x = ([1,2,3], [4,5,6], [5,6,7])

([1, 2, 3], [4, 5, 6], [5, 6, 7])

In [79]:
np.random.randint(0,10,(3,4))

array([[0, 4, 0, 7],
       [4, 0, 5, 4],
       [4, 6, 8, 4]])

In [80]:
np.random.normal(0,1,(3,4))

array([[ 0.26117021, -0.61559467,  1.11683941, -0.91477444],
       [-1.51190222, -0.43146512,  0.48493077, -0.23488465],
       [ 0.28910967, -0.64706474, -0.73171182,  1.31979443]])

In [85]:
np.random.random((3,4))

array([[0.44010384, 0.26422187, 0.32232064, 0.90612768],
       [0.42360057, 0.69284874, 0.84528308, 0.6521209 ],
       [0.62927644, 0.76953936, 0.76557469, 0.07966171]])

In [93]:
np.eye(10000)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [96]:
np.linspace(0,.05,100)

array([0.        , 0.00050505, 0.0010101 , 0.00151515, 0.0020202 ,
       0.00252525, 0.0030303 , 0.00353535, 0.0040404 , 0.00454545,
       0.00505051, 0.00555556, 0.00606061, 0.00656566, 0.00707071,
       0.00757576, 0.00808081, 0.00858586, 0.00909091, 0.00959596,
       0.01010101, 0.01060606, 0.01111111, 0.01161616, 0.01212121,
       0.01262626, 0.01313131, 0.01363636, 0.01414141, 0.01464646,
       0.01515152, 0.01565657, 0.01616162, 0.01666667, 0.01717172,
       0.01767677, 0.01818182, 0.01868687, 0.01919192, 0.01969697,
       0.02020202, 0.02070707, 0.02121212, 0.02171717, 0.02222222,
       0.02272727, 0.02323232, 0.02373737, 0.02424242, 0.02474747,
       0.02525253, 0.02575758, 0.02626263, 0.02676768, 0.02727273,
       0.02777778, 0.02828283, 0.02878788, 0.02929293, 0.02979798,
       0.03030303, 0.03080808, 0.03131313, 0.03181818, 0.03232323,
       0.03282828, 0.03333333, 0.03383838, 0.03434343, 0.03484848,
       0.03535354, 0.03585859, 0.03636364, 0.03686869, 0.03737

In [99]:
np.random.normal(0,1,(3,3))

array([[-0.42952128,  0.49394603, -0.41800211],
       [-0.64371185, -0.3477739 ,  0.38982487],
       [-1.48415367,  1.13180874,  0.04601491]])

In [100]:
x = 10

In [101]:
y = x

In [102]:
y = 20

In [103]:
x

10

In [104]:
x = [10,]

In [105]:
y = x

In [106]:
y = [20,]

In [107]:
x

[10]